### PR TITLE
AP-4683 updated WebhookEndpoint code to use UUIDs

### PR DESCRIPTION
**Pull request by donnen**

### CODE REVIEW

**Comment by donnen** [comment]
Also removed outdated spec.

**Comment by CullenShane** [comment]
Once this is merged it should trigger a build in Circle now.

Also!  Is this the way that we refer to ids in this gem?  I thought uuids were just always called ids?

**Comment by CullenShane** [comment]
For instance, order has an ID, not an uuid.  but the serializer is sending a UUID in the id field.  This is probably how this should act as well.

Do the docs mention WebhookEndpoint.uuid or WebhookEndpoint.id?

**Comment by donnen** [comment]
That's a good point. The rest of the gem uses ID. In that case there is really nothing to change.

**Comment by CullenShane** [comment]
We still need to remove that paymentRequest spec though

**Comment by CullenShane** [comment]
👍

**Comment by tcochran317** [comment]
👍

**Pull request merged**
